config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'concerts#index'
  resources :songs
  resources :singers
  resources :concerts
  resources :pictures
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/singer.rb
class Singer < ApplicationRecord
	has_and_belongs_to_many :concerts
	has_and_belongs_to_many :songs	

	include ImageUploader::Attachment.new(:image)
	include PhotoUploader::Attachment.new(:photo)
end

app/controllers/singers_controller.rb
class SingersController < ApplicationController
  before_action :set_singer, only: [:show, :edit, :update, :destroy]

  helper_method :sort_column, :sort_direction

  @column = "last_name"
  @direction = "asc"

  # GET /singers
  # GET /singers.json
  def index
    #@singers = Singer.all
    authorize Singer
    @q = Singer.search(params[:q])
    @singers = @q.result(distinct: true)
    @singers = @singers.order("#{sort_column} #{sort_direction}")
  end

  # GET /singers/1
  # GET /singers/1.json
  def show
    authorize Singer
  end

  # GET /singers/new
  def new
    @singer = Singer.new
    authorize @singer
  end

  # GET /singers/1/edit
  def edit
    skip_authorization
    @singers = policy_scope(Singer)

  end

  # POST /singers
  # POST /singers.json
  def create
    @singer = Singer.new(singer_params)
    authorize @singer

    respond_to do |format|
      if @singer.save
        format.html { redirect_to @singer, notice: 'Singer was successfully created.' }
        format.json { render :show, status: :created, location: @singer }
      else
        format.html { render :new }
        format.json { render json: @singer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /singers/1
  # PATCH/PUT /singers/1.json
  def update
    #authorize @singer
    skip_authorization
    respond_to do |format|
      if @singer.update(singer_params)
        format.html { redirect_to @singer, notice: 'Singer was successfully updated.' }
        format.json { render :show, status: :ok, location: @singer }
      else
        format.html { render :edit }
        format.json { render json: @singer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /singers/1
  # DELETE /singers/1.json
  def destroy
    authorize @singer
    @singer.destroy
    respond_to do |format|
      format.html { redirect_to singers_url, notice: 'Singer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_singer
      @singer = Singer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def singer_params
      params.require(:singer).permit( :photo1_caption, :photo2_caption, :photo, :remove_photo, :image, :remove_image, :last_name, :first_name, :email, :voice, :joined, :left, :join_year, :left_year, :notes, {:concert_ids => []}, {:song_ids => []})
    end

    def sortable_columns
      [ "last_name", "first_name","email", "voice"]
    end

    def sort_column
      #puts "CH  #{@column} #{@direction}"
      sortable_columns.include?(params[:column]) ? params[:column] : "last_name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/singers_helper.rb
module SingersHelper
end

app/views/singers/_form.html.erb
<%= form_for(singer) do |f| %>
  <% if singer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(singer.errors.count, "error") %> prohibited this singer from being saved:</h2>

      <ul>
      <% singer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :last_name %>:
    <%= f.text_field :last_name %>
    -:-
    <%= f.label :first_name %>:
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :email %>:
    <%= f.text_field :email %>
    -:-
    <%= f.label :voice %>:
    <%= f.text_field :voice %>
  </div>

  <div class="field">
    <%= f.label :joinYear %>:
    <%= f.number_field :join_year %>
    -:-
    <%= f.label :leftYear %>:
    <%= f.number_field :join_year %>
  </div>

  <div class="field">
    <%= f.label :notes %>:
    <%= f.text_area :notes %>
  </div>

  <div class = "field">
    <%= f.label :image, "Photo1", :style => "inline" %>: <small><i>(Note: Maximum photo size is 2 megabytes)</i></small>
    <%= f.file_field :image %> 
  </div>
  <% if @singer.image_data? %>
    <div class = "field">
      <% if !@singer.image[:thumb].nil? %>
        <%= image_tag @singer.image_url(:thumb) %>
      <% end %>
      <%= f.label :photo1_caption, "Photo1 Caption:" %>
      <%= f.text_field :photo1_caption, :size => 40 %>
    </div>
    <div class = "field">
      Remove attachment: <%= f.check_box :remove_image %>
    </div>
  <% end %>

  <div class = "field">
    <%= f.label :photo, "Photo2", :style => "inline" %>: <small><i>(Note: Maximum photo size is 2 megabytes)</i></small>
    <%= f.file_field :photo %>
  </div>
  <% if @singer.photo_data? %>
    <div class = "field">
      <% if !@singer.photo[:thumb].nil? %>
        <%= image_tag @singer.photo_url(:thumb) %>
      <% end %>
        <%= f.label :photo2_caption, "Photo2 Caption:" %>
        <%= f.text_field :photo2_caption, :size => 40 %>
    </div>
    <div class = "field">
      Remove attachment: <%= f.check_box :remove_photo %>
    </div>
  <% end %>

<div><strong> Concerts Appeared In: </strong></div>

  <div class="field"> 
   <% for concert in Concert.all.order(:concert_year) %>
     <% if (true)%>
       <%= check_box_tag "singer[concert_ids][]", concert.id, @singer.concerts.include?(concert) %>
       <%= concert.concert_year.to_s + '-' + concert.name[0..20] %>
     <% end %>
   <%end%>
  </div>
<p></p>

  <div><strong> Soloist In:  </strong></div>
  <div class="field">
   <% for song in Song.all.order(:name) %>
     <% if (true)%>
       <%= check_box_tag "singer[song_ids][]", song.id, @singer.songs.include?(song) %>
       <%= song.name %>
     <% end %>
     |
   <%end%>
<p></p>

  <div class="actions">
    <%= f.submit 'Save Singer', :class => 'btn btn-success btn-sm active' %>
  </div>
<% end %>
<p></p>

app/views/singers/edit.html.erb
<h1>Editing Singer</h1>

<%= render 'form', singer: @singer %>
<%= link_to "Back-don't save", singers_path, :class => 'btn btn-warning btn-sm active' %>

<% if false %>
<%= link_to 'Show', @singer %> |
<% end %>

app/views/singers/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Singers</h3>
<h5>Total Count: <%= Singer.count %></h5>

<% can = policy(Singer).create? %>

<%= search_form_for @q do |f| %>
    <%= f.submit "Search by:", :class => 'btn btn-info btn-sm active' %>  &nbsp &nbsp ->
    <%= f.label :last_name_cont, "Last Name:", :style => "display: inline-block" %>
    <%= f.search_field :last_name_cont, :id => "searchfpn" %>
    <%= f.label :voice_cont, "Voice:", :style => "display: inline-block" %>
    <%= f.search_field :voice_cont, :id => "searchfpn" %> &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
    <% if can %><%= link_to 'New Singer', new_singer_path, :class => 'btn btn-success btn-sm active margin-left: 35px;' %><% end %>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= sort_link "last_name", "Last Name" %></th>
      <th><%= sort_link "first_name", "First Name" %></th>
      <% if policy(Singer).update?  || (user_signed_in? && current_user.member?) %>
        <th><%= sort_link "email" %></th>
      <% end %>
      <th><%= sort_link "voice" %></th>
      <th>Joined</th>
      <th>Left</th>
      <th>Notes</th>
      <th><%= link_to 'Concerts', concerts_path %></th>
      <th><%= link_to 'Solos', songs_path %></th>
 
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
    <% @singers.each do |singer| %>
      <tr>
        <td><%= link_to "#{singer.last_name}", singer %></td>
        <td><%= singer.first_name %></td>
        <% if policy(singer).update? || (user_signed_in? && current_user.member?) %>
          <td><%= singer.email %></td>
        <% end %>  
        <td><%= singer.voice %></td>
        <td><%= singer.join_year %></td>
        <td><%= singer.left_year %></td>
        <td><%= singer.notes %></td>
        <td><%= singer.concerts.count %></td>
        <td><%= singer.songs.count %></td>
        <% if false %><td><%= link_to 'Show', singer %></td><% end %>
        <% if policy(singer).update? %>
          <td><%= link_to 'Edit', edit_singer_path(singer), :class => 'btn btn-success btn-sm active' %></td>
          <td><%= link_to 'Destroy', singer, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-sm active' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can %><%= link_to 'New Singer', new_singer_path, :class => 'btn btn-success btn-sm active' %><% end %>
<% if false %>
<%= link_to 'Concerts', concerts_path %>
<%= link_to 'Songs', songs_path %>
<% end %>

app/views/singers/new.html.erb
<h1>New Singer</h1>

<%= render 'form', singer: @singer %>

<%= link_to "Back - Don't Save", singers_path, :class => 'btn btn-warning btn-sm active'  %>

app/views/singers/show.html.erb
<h2>Singer</h2>

<p>
  <strong>Name:</strong>
  <%= @singer.first_name %>
  <%= @singer.last_name %> -:-
  <strong>Voice:</strong>
  <%= @singer.voice %>
</p>

<% if policy(Singer).update? %>
  <p>
    <strong>Email:</strong>
    <%= @singer.email %>
  </p>
<% end %>

<p>
  <strong>Joined:</strong>
  <%= @singer.join_year %>
  -:- 
  <strong>Left:</strong>
  <%= @singer.left_year %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @singer.notes %>
</p>

<p>
  <strong>Photo1: </strong>
  <% if @singer.image_data && !@singer.image[:original].nil? %>
    <strong>Original Filename: </strong> <%= @singer.image[:original].original_filename %> -:-
    <strong>Size: </strong> <%= number_with_delimiter(@singer.image[:original].size) %> kb -:-
    <strong>Height: </strong> <%= @singer.image[:original].height %> -:-
    <strong>Width: </strong> <%= @singer.image[:original].width %> -:-
    <strong>ID: </strong> <%= @singer.image[:original].id %>
  <% end %>
</p><p>
  <% if @singer.image_data && !@singer.image[:small].nil? %>
    <%= image_tag @singer.image_url(:small) %> 
 </p><p>
    <%= @singer.photo1_caption %> -:->
    <%= link_to 'Click here for original (full size) photo', @singer.image_url(:original) %>
  <% end %>
</p>

<p>
  <strong>Photo2: </strong>
  <% if @singer.photo_data && !@singer.photo[:original].nil? %>
    <strong>Original Filename: </strong> <%= @singer.photo[:original].original_filename %> -:-
    <strong>Size: </strong> <%= number_with_delimiter(@singer.photo[:original].size) %> kb -:-
    <strong>Height: </strong> <%= @singer.photo[:original].height %> -:-
    <strong>Width: </strong> <%= @singer.photo[:original].width %> -:-
    <strong>ID: </strong> <%= @singer.photo[:original].id %>
  <% end %>
  </p><p>
  <% if @singer.photo_data && !@singer.photo[:thumb].nil? %>
    <%= image_tag @singer.photo_url(:thumb) %> 
  </p><p>
    <%= @singer.photo2_caption %> -:->
    <%= link_to 'Click here for original (full size) photo', @singer.photo_url(:original) %>
  <% end %>
</p>

<p>
  <strong>Concerts:</strong><br />
  <% @singer.concerts.order(:concert_year).in_groups_of(8,false) do |concrts| %>
    <% for concert in concrts %>
      <td><%= link_to concert.concert_year.to_s + '-' + concert.name[0..20], concert_path(concert.id) %></td>
      -:- 
    <% end %>
    <br />
  <% end %>
</p>

<p>
  <strong>Soloist In:</strong>
  <% @singer.songs.order(:name).each do |t| %>
    <td><%= link_to t.name, song_path(t.id) %></td>
    -:- 
  <% end %>
</p>

<%= link_to 'Back', singers_path, :class => 'btn btn-primary btn-sm active' %>     |   

<% if policy(Singer).update? || ( user_signed_in? && current_user.email == @singer.email ) %>
  <%=  puts "singer email #{@singer[:email]} user emails #{current_user.email}" %>
  <%= link_to 'Edit', edit_singer_path(@singer), :class => 'btn btn-warning btn-sm active' %> |
<% end %>

<% if policy(Singer).create? %>
  <%= link_to 'New Singer', new_singer_path, :class => 'btn btn-success btn-sm active' %>
<% end %>