config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'concerts#index'
  resources :songs
  resources :singers
  resources :concerts
  resources :pictures
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/song.rb
class Song < ApplicationRecord
	has_many :programs
	has_many :concerts, :through => :programs

	has_and_belongs_to_many :singers
	#has_and_belongs_to_many :songs

	attr_accessor :s_o1, :s_o2, :s_o3, :s_o4
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  helper_method :sort_column, :sort_direction

  # GET /songs
  # GET /songs.json
  def index
    #@songs = Song.all
    authorize Song
    @q = Song.search(params[:q])
    @songs = @q.result(distinct: true)
    @songs = @songs.order("#{sort_column} #{sort_direction}")
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    authorize Song
  end

  # GET /songs/new
  def new
    @song = Song.new
    authorize @song
  end

  # GET /songs/1/edit
  def edit
    authorize @song
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)
    authorize @song

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    authorize @song
            
     respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
        #songs = Song.all
        #byebug
        #puts "got here - #{params[:song][:concert_ids]} - #{@song.id} - #{params[:song][:s_o]} - #{params[:song][:s_o1]}"
        if !params[:song][:concert_ids][0].nil?
          @program = Program.find_by_concert_id_and_song_id(params[:song][:concert_ids][0],@song.id)
          @program.song_order = params[:song][:s_o]
          @program.save
          puts "Song Id: #{@song.id} Concert ID: #{params[:song][:concert_ids][0]} Song Name: #{@song.name} Song Order: #{@program.song_order}"
        end
       if !params[:song][:concert_ids][1].nil?
          @program = Program.find_by_concert_id_and_song_id(params[:song][:concert_ids][1],@song.id)
          @program.song_order = params[:song][:s_o1 ]
          @program.save
          puts "Song Id: #{@song.id} Concert ID: #{params[:song][:concert_ids][1]} Song Name: #{@song.name} Song Order: #{@program.song_order}"
        end
       if !params[:song][:concert_ids][2].nil?
          @program = Program.find_by_concert_id_and_song_id(params[:song][:concert_ids][2],@song.id)
          @program.song_order = params[:song][:s_o2 ]
          @program.save
          puts "Song Id: #{@song.id} Concert ID: #{params[:song][:concert_ids][2]} Song Name: #{@song.name} Song Order: #{@program.song_order}"
        end
       if !params[:song][:concert_ids][3].nil?
          @program = Program.find_by_concert_id_and_song_id(params[:song][:concert_ids][3],@song.id)
          @program.song_order = params[:song][:s_o3 ]
          @program.save
          puts "Song Id: #{@song.id} Concert ID: #{params[:song][:concert_ids][3]} Song Name: #{@song.name} Song Order: #{@program.song_order}"
        end
       if !params[:song][:concert_ids][4].nil?
          @program = Program.find_by_concert_id_and_song_id(params[:song][:concert_ids][4],@song.id)
          @program.song_order = params[:song][:s_o4 ]
          @program.save
          puts "Song Id: #{@song.id} Concert ID: #{params[:song][:concert_ids][4]} Song Name: #{@song.name} Song Order: #{@program.song_order}"
        end

        if false
        for concert in Concert.all
          if !concert.songs.find_by_name(@song.name).nil?
            sid = concert.songs.find_by_name(@song.name).id   # get id of song in this concert
            @program = Program.find_by_concert_id_and_song_id(concert.id,sid)           # create program instance
            #@program.nil?
            @program.song_order = @song[:s_o]                  # update value
            #puts "Song Id: #{sid} Concert ID: #{concert.id} Song Name: #{@song.name} Song Order: #{@song[:s_o]}"
            @program.save      
          end                               # save it
        end     
        end

      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    authorize @song
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :source, :composer, :lyricist, :arranger, :genre, :song_type, :notes, {:singer_ids => []}, {:concert_ids => []}, :s_o,:s_o1,:s_o2,:s_o3,:s_o4, programs_attributes: [ :song_order ] )
    end

    def sortable_columns
      ["name", "source", "composer","lyricist","arranger","genre","song_type"]
    end

    def sort_column
      sortable_columns.include?(params[:column]) ? params[:column] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_for(song) do |f| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :source %>
    <%= f.text_field :source %>
  </div>

  <div class="field">
    <%= f.label :composer %>
    <%= f.text_field :composer %>
  </div>

  <div class="field">
    <%= f.label :lyricist %>
    <%= f.text_field :lyricist %>
  </div>

  <div class="field">
    <%= f.label :arranger %>
    <%= f.text_field :arranger %>
  </div>

  <div class="field">
    <%= f.label :genre %>
    <%= f.text_field :genre %>
  </div>

  <div class="field">
    <%= f.label :Type %>
    <%= f.text_field :song_type %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div><strong>Concerts: </strong></div>

 <div class="field">
   <% for concert in Concert.all.order(:concert_year) %>
     <% if (true)%>
       <%= check_box_tag "song[concert_ids][]", concert.id, @song.concerts.include?(concert) %>
       <%= concert.concert_year.to_s + '-' + concert.name[0..20] %>
     <% end %>
     | 
   <%end%>
  </div>

  <div class="field">
    <% @count = 0 %>
    <% so = [0,0,0,0,0] %>
    <% for concert in Concert.all.order(:concert_year) %>  
      <% if !concert.songs.find_by_name(song.name).nil? %>
        <% so[@count] = Program.find_by_concert_id_and_song_id(concert.id,song.id).song_order
            if (so[@count].nil?)
              song.s_o = 0
            elsif (@count == 0)    #crappy code because I don't fully understand using input hash arrays
              @c_o = concert.id
              song.s_o = so[@count]
            elsif (@count == 1)
              @c_o1 = concert.id
              song.s_o1 = so[@count]
            elsif (@count == 2)
              @c_o2 = concert.id
              song.s_o2 = so[@count]
            elsif (@count == 3)
              @c_o3 = concert.id
              song.s_o3 = so[@count]
            elsif (@count == 4)
              @c_o4 = concert.id
              song.s_o4 = so[@count]
           end %>
        <strong><%= concert.concert_year %></strong>
        <%= f.label( " Song Order: " ) %>
          <% if @count == 0 %>
            <%= f.number_field :s_o, in: 0..30, size: 3 %>
          <% elsif @count == 1 %>
            <%= f.number_field :s_o1, in: 0..30, size: 3 %>
         <% elsif @count == 2 %>
            <%= f.number_field :s_o2, in: 0..30, size: 3 %>
         <% elsif @count == 3 %>
            <%= f.number_field :s_o3, in: 0..30, size: 3 %>
         <% elsif @count == 4 %>
            <%= f.number_field :s_o4 , in: 0..30, size: 3 %>
          <% end %>
        <% puts "got here - #{@count} - #{so[@count]} - #{@c_o} - #{@c_o1} > #{concert.id}" %>  
        <% @count += 1 %>
      <% end %>
    <% end %>
  </div>

  <p></p>

  <div><strong> Soloists:  </strong></div>

  <div class="field">
   <% for singer in Singer.all.order(:last_name) %>
     <% if (true)%>
       <%= check_box_tag "song[singer_ids][]", singer.id, @song.singers.include?(singer) %>  
       <%= singer.first_name[0] + " " + singer.last_name %>
     <% end %>
     |
   <%end%>
<p></p>

   <div class="actions">
    <%= f.submit 'Save Song', :class => 'btn btn-success btn-sm active' %>
  </div>

<% end %>
<p></p>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>
<%= link_to "Back - Don't Save", songs_path, :class => 'btn btn-warning btn-sm active' %>

<% if false %>
<%= link_to 'Show', @song %> |
<% end %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Songs</h3>
<h5>Total Count: <%= Song.count %></h5>

<% can = policy(Song).create? %>

<%= search_form_for @q do |f| %>
    <%= f.submit "Search by:", :class => 'btn btn-info btn-sm active' %> &nbsp &nbsp ->
    <%= f.label :name_cont, "Name:", :style => "display: inline-block" %>
    <%= f.search_field :name_cont, :id => "searchfpn" %> ->
    <%= f.label :composer_cont, "Composer:", :style => "display: inline-block" %>
    <%= f.search_field :composer_cont, :id => "searchfpn" %> ->
    <%= f.label :genre_cont, "Genre:", :style => "display: inline-block" %>
    <%= f.search_field :genre_cont, :id => "searchfpn" %> &nbsp | &nbsp
    <% if can %>
      <%= link_to 'New Song', new_song_path, :class => 'btn btn-success btn-sm active' %>
    <% end %>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= sort_link "name" %></th>
      <th><%= sort_link "source" %></th>
      <th><%= sort_link "composer" %></th>
      <th><%= sort_link "lyricist" %></th>
      <th><%= sort_link "arranger" %></th>
      <th><%= sort_link "genre" %></th>
      <th><%= sort_link "song_type", "Type" %></th>
      <th><%= "Year" %></th>
      <th>Notes</th>
      <th><%= link_to 'Concerts', concerts_path %></th>
      <th><%= link_to 'Solos', singers_path %></th>


      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
    <% @songs.each do |song| %>
      <tr>
        <td><%= link_to "#{song.name[0..20]}", song %></td>
        <td><%= song.source[0..20] %></td>
        <td><%= song.composer[0..20] %></td>
        <td><%= song.lyricist[0..20] %></td>
        <td><%= song.arranger %></td>
        <td><%= song.genre %></td>
        <td><%= song.song_type %></td>
        <td><%= if song.concerts.nil? then song.concerts.first.concert_year end %></td>
        <td><%= song.notes %></td>
        <td><%= song.concerts.count %></td>
        <td><%= song.singers.count %></td>
        <% if false %><td><%= link_to 'Show', song %></td><% end %>
        <% if policy(song).update? %>
          <td><%= link_to 'Edit', edit_song_path(song), :class => 'btn btn-success btn-sm active' %></td>
          <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-sm active' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can %>
  <%= link_to 'New Song', new_song_path, :class => 'btn btn-success btn-sm active' %>
<% end %>

<% if false %>
<%= link_to 'Concerts', concerts_path %>
<%= link_to 'Singers', singers_path %>
<% end %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to "Back - Don't Save", songs_path, :class => 'btn btn-warning btn-sm active'  %>

app/views/songs/show.html.erb
<h3> Songs </h3>

<p>
  <strong>Name:</strong>
  <%= @song.name %>
</p>

<p>
  <strong>Source:</strong>
  <%= @song.source %>
</p>

<p>
  <strong>Composer:</strong>
  <%= @song.composer %>
</p>

<p>
  <strong>Lyricist:</strong>
  <%= @song.lyricist %>
</p>

<p>
  <strong>Arranger:</strong>
  <%= @song.arranger %>
</p>

<strong>Genre:</strong>
  <%= @song.genre %>
</p>

<p>
  <strong>Type:</strong>
  <%= @song.song_type %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @song.notes %>
</p>

<p>
  <strong>In Concerts: </strong>
  <% @song.concerts.order(:concert_year).each do |t| %>
    <td><%= link_to t.concert_year.to_s + '-' + t.name, concert_path(t.id) %></td>
    -:- 
  <% end %>
</p>

<p>
<% for concert in Concert.all.order(:concert_year) %>
      <% if !concert.songs.find_by_id(@song.id).nil? %>
        <% cy = concert.concert_year %>
        <% cid = concert.id %>
        <strong>Song Order 
        <%= "#{cy}" %>: </strong>
        <%= Program.find_by_concert_id_and_song_id(cid,@song.id).song_order %> -:-
      <% end %>
    <% end %>
</p>

<p>
  <strong>Soloists:</strong>
  <% @song.singers.order(:last_name).each do |t| %>
    <td><%= link_to t.first_name[0]+" "+t.last_name, singer_path(t.id) %></td>
    -:-  
  <% end %>
</p>

<%= link_to 'Back', songs_path, :class => 'btn btn-primary btn-sm active' %>     |   

<% if policy(Song).update? %>
  <%= link_to 'Edit', edit_song_path(@song), :class => 'btn btn-warning btn-sm active' %> |
<% end %>

<% if policy(Song).create? %>
  <%= link_to 'New Song', new_song_path, :class => 'btn btn-success btn-sm active' %>
<% end %>

<% if false %>
<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %> |
<%= link_to 'Add New Song', new_song_path %>
<% end %>