config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'concerts#index'
  resources :songs
  resources :singers
  resources :concerts
  resources :pictures
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/concert.rb
class Concert < ApplicationRecord
	has_and_belongs_to_many :singers

	#has_and_belongs_to_many :dep_songs,
	#	join_table: :concerts_songs, class_name: Song,
	#	association_foreign_key: :song_id

	has_many :programs
	has_many :songs, :through => :programs
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: [:show, :edit, :update, :destroy]

  helper_method :sort_column, :sort_direction

  #current_or_guest_user

  # GET /concerts
  # GET /concerts.json
  def index

    current_or_guest_user
    authorize Concert
    #@concerts = Concert.all
    @q = Concert.search(params[:q])
    @concerts = @q.result(distinct: true)
    @concerts = @concerts.order("#{sort_column} #{sort_direction}")
  end

  # GET /concerts/1
  # GET /concerts/1.json
  def show
    authorize Concert
    @song_sort = true
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
    authorize @concert
  end

  # GET /concerts/1/edit
  def edit
    authorize Concert
  end

  # POST /concerts
  # POST /concerts.json
  def create
    @concert = Concert.new(concert_params)
    authorize @concert

    respond_to do |format|
      if @concert.save
        format.html { redirect_to @concert, notice: 'Concert was successfully created.' }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1
  # PATCH/PUT /concerts/1.json
  def update
    authorize @concert
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to @concert, notice: 'Concert was successfully updated.' }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1
  # DELETE /concerts/1.json
  def destroy
    authorize @concert
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to concerts_url, notice: 'Concert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concert_params
      params.require(:concert).permit(:name, :venue, :concertdate, :conductor, :accompanist, :theme, :notes, :concert_year, :narrators, {:singer_ids => []}, {:song_ids => []}, :sort, :song_order)
    end

    def sortable_columns
      ["concert_year", "name", "venue", "concertdate"]
    end

    def sort_column
      sortable_columns.include?(params[:column]) ? params[:column] : "concert_year"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end
end

app/helpers/concerts_helper.rb
module ConcertsHelper
	
end

app/views/concerts/_form.html.erb
<%= form_for(concert) do |f| %>
  <% if concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
      <% concert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %>
    <%= f.number_field :concert_year, class: :text_field, step: :any %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :venue %>
    <%= f.text_field :venue %> -|-
  
    <%= f.label :concertdate %>
    <%= f.date_select :concertdate, start_year: 1988 %>
  </div>

  <div class="field">
    <%= f.label :conductor %>
    <%= f.text_field :conductor %> -|-

    <%= f.label :accompanist %>
    <%= f.text_field :accompanist %> -|-

    <%= f.label :narrators %>
    <%= f.text_field :narrators %>
  </div>

  <div class="field">
    <%= f.label :theme %>
    <%= f.text_area :theme %>
     | 
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div><b> | Singers | </b></div>

  <div class="field"> 
   <%# for singer in Singer.all.order(:last_name) %>
   <% Singer.all.sort_by{|singer| (singer.last_name)}.in_groups_of(12,false).each do |singer_array| %>
     <% singer_array.each do |singer| %>
      <% if (true) %>
       <%= check_box_tag "concert[singer_ids][]", singer.id, @concert.singers.include?(singer) %>
       <%= singer.first_name[0] + ". " + singer.last_name %> -:-
      <% end %>
    <% end %>
    <br />
   <%end%>
  </div>
<p></p>

  <div><b>  | Songs | </b></div>
  <div class="field">
   <% for song in Song.all.order(:name) %>
     <% if (true)%>
       <%= check_box_tag "concert[song_ids][]", song.id, @concert.songs.include?(song) %>
       <%= song.name[0..15] %> -:-
     <% end %>
   <%end%>
</div>
<p></p> 

  <div class="actions">
    <%= f.submit 'Save Concert', :class => 'btn btn-success btn-sm active' %>
  </div>
<% end %>
<p></p>

app/views/concerts/edit.html.erb
<h1>Editing Concert</h1>

<%= render 'form', concert: @concert %>
<%= link_to "Back-don't save", concerts_path, :class => 'btn btn-warning btn-sm active' %>

<% if false %>
<%= link_to 'Show', @concert %> |
<% end %>

app/views/concerts/index.html.erb
<h3>Concerts</h3>
<h5>Total Count: <%= Concert.count %></h5>

<% can = policy(Concert).create? %>

<%= search_form_for @q do |f| %>
    <%= f.submit "Search by:", :class => 'btn btn-info btn-sm active' %> &nbsp &nbsp ->
    <%= f.label :concert_year_eq, "Year=", :style => "display: inline-block" %>
    <%= f.search_field :concert_year_eq, :id => "searchfpn" %> ->
    <%= f.label :name_cont, "Name contains=", :style => "display: inline-block" %>
    <%= f.search_field :name_cont, :id => "searchfpn" %> &nbsp | &nbsp ->
    <%= f.label :venue_cont, "Venue contains=", :style => "display: inline-block" %>
    <%= f.search_field :venue_cont, :id => "searchfpn" %> &nbsp &nbsp &nbsp &nbsp&nbsp &nbsp &nbsp | &nbsp ->

    <% if  can %><%= link_to 'New Concert', new_concert_path, :class => 'btn btn-success btn-sm active' %><% end %>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= sort_link "concert_year", "Year" %></th>
      <th><%= sort_link "name" %></th>
      <th><%= sort_link "venue" %></th>
      <th><%= sort_link "concertdate", "Date" %></th>
      <th><%= "Conductor" %></th>
      <th><%= "Accompanist" %></th>
      <th><%= "Narrators" %></th>
      <th style="width:5em"><%= "Theme" %></th>
      <th style="width:5em"><%= "Notes" %></th>
      <th><%= link_to 'Songs', songs_path %></th>
      <th><%= link_to 'Singers', singers_path %></th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @concerts.each do |concert| %>
      <tr>
        <td><%= link_to "-#{concert.concert_year}-", concert %></td>
        <td><%= concert.name %></td>
        <td><%= concert.venue %></td>
        <td><%= concert.concertdate.strftime("%m/%d/%y") %></td>
        <td><%= concert.conductor %></td>
        <td><%= concert.accompanist %></td>
        <td><%= concert.narrators %></td>
        <td><%= concert.theme[0..5] %>
          <% if concert.theme.length > 5 %>
            <%= '..'  %>
          <% end %></td>
        <td><%= concert.notes[0..5] %>
            <% if concert.notes.length > 5 %>
            <%= '..'  %>
          <% end %></td>
        <td><%= concert.songs.count %></td>
        <td><%= concert.singers.count %></td>
        <% if false %> <td><%= link_to 'Show', concert, :class => 'btn btn-success btn-sm active'  %></td><% end %>
        <% if policy(concert).update? %>
          <td><%= link_to 'Edit', edit_concert_path(concert), :class => 'btn btn-warning btn-sm active'  %></td>
          <td><%= link_to 'Destroy', concert, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-sm active'  %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if  can %><%= link_to 'New Concert', new_concert_path, :class => 'btn btn-success btn-sm active' %><% end %>

app/views/concerts/new.html.erb
<h1>New Concert</h1>

<%= render 'form', concert: @concert %>

<%= link_to "Back - Don't Save", concerts_path, :class => 'btn btn-warning btn-sm active'  %>

app/views/concerts/show.html.erb
<h3> Concert </h3>

<p>
  <strong>Year:</strong>
  <%= @concert.concert_year %>
</p>

<p>
  <strong>Name:</strong>
  <%= @concert.name %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @concert.venue %>
</p>

<p>
  <strong>Concertdate:</strong>
  <%= @concert.concertdate %>
</p>

<p>
  <strong>Conductor:</strong>
  <%= @concert.conductor %>
</p>

<p>
  <strong>Accompanist:</strong>
  <%= @concert.accompanist %>
</p>

<p>
  <strong>Narrators:</strong>
  <%= @concert.narrators %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @concert.theme %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @concert.notes %>
</p>

<p>
  <strong>Singers:</strong>
    <% @concert.singers.sort_by{|singer| (singer.last_name)}.in_groups_of(20,false).each do |t_array| %>
      <% t_array.each do |t| %>
        <td><%= link_to t.first_name[0]+" "+t.last_name, singer_path(t.id) %></td>
        -:- 
        <% end %>
      <br />
    <% end %>
</p>

<p>
  <strong></strong>

      <% Program.where(concert_id: [@concert.id]).each do |so| %>
        <% if so.song_order.nil? 
            @song_sort = false 
          end %>
      <% end %>

      <% if !@song_sort %>
          <strong> Songs Sorted by Name: </strong>          
          <% @concert.songs.sort_by{|song| (song.name)}.each do |t| %>
          <td><%= link_to t.name, song_path(t.id) %></td>
          -:- 
      <% end %>
      <% else %>
        <div class-"container">
        <strong> Songs Sorted by Program Order: </strong><br />
        <% count = 1 %>
        <% @concert.songs.sort_by{|song| (Program.find_by_song_id_and_concert_id(song.id,@concert.id).song_order) || 1}.in_groups_of(6,false).each do |t_array| %>
          <div class="row" >
          <% t_array.each do |t| %>
            <div class="col-sm-2">
              <%= count.to_s + "-" %>
              <td><%= link_to t.name[0..30], song_path(t.id) %></td>
            </div>
            <% count += 1 %>
          <% end %>
          </div>
        <% end %>
        </div>
    <% end %>
</p>

<%= link_to 'Back', concerts_path, :class => 'btn btn-primary btn-sm active' %>     |   

<% if policy(Concert).update? %>
  <%= link_to 'Edit', edit_concert_path(@concert), :class => 'btn btn-warning btn-sm active' %> |
<% end %>

<% if policy(Concert).create? %>
  <%= link_to 'New Concert', new_concert_path, :class => 'btn btn-success btn-sm active' %> |
<% end %>

<% if policy(Singer).create? %>
  <%= link_to 'New Singer', new_singer_path, :class => 'btn btn-success btn-sm active' %> |
<% end %>

<% if policy(Song).create? %>
  <%= link_to 'New Song', new_song_path, :class => 'btn btn-success btn-sm active' %> |
<% end %>

<% if false %>
<%= link_to 'Edit', edit_concert_path(@concert) %> |
<%= link_to 'Back', concerts_path %>
<% end %>