config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'concerts#index'
  resources :songs
  resources :singers
  resources :concerts
  resources :pictures
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/picture.rb
class Picture < ApplicationRecord

include PictureUploader::Attachment.new(:picture)
end

app/models/song.rb
class Song < ApplicationRecord
	has_many :programs
	has_many :concerts, :through => :programs

	has_and_belongs_to_many :singers
	#has_and_belongs_to_many :songs

	attr_accessor :s_o1, :s_o2, :s_o3, :s_o4
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_singer, only: [:show, :edit, :update, :destroy]

  helper_method :sort_column, :sort_direction

  @column = "caption"
  @direction = "asc"

  # GET /pictures
  # GET /pictures.json
  def index
    #@singers = Singer.all
    authorize Picture
    @q = Picture.search(params[:q])
    @pictures = @q.result(distinct: true)
    @pictures = @pictures.order("#{sort_column} #{sort_direction}")
  end

  # GET /pictures/1
  # GET /picturess/1.json
  def show
    authorize Picture
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
    authorize @picture
  end

  # GET /pictures/1/edit
  def edit
    skip_authorization
    @pictures = policy_scope(Picture)

  end

  # POST /singers
  # POST /singers.json
  def create
    @picture = Picture.new(picture_params)
    authorize @picture

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    authorize @picture
    skip_authorization
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    authorize @picture
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Singer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_singer
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit( :picture, :remove_picture, :caption, :picture_date, :notes, :submitted_by )
    end

    def sortable_columns
      [ "caption", "picture_date", "submitted_by"]
    end

    def sort_column
      #puts "CH  #{@column} #{@direction}"
      sortable_columns.include?(params[:column]) ? params[:column] : "caption"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/views/pictures/_form.html.erb
<%= form_for(picture) do |f| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :caption %>
    <%= f.text_field :caption %>
  </div>

  <div class="field">
    <%= f.label :picture_date %>
    <%= f.date_field :picture_date %>
  </div>

  <div class="field">
    <%= f.label :submitted_by %>
    <%= f.text_field :submitted_by %>
  </div>

   <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div class = "field">
    <%= f.label :picture, :style => "inline" %>:
    <%= f.file_field :picture %>
    Note: Maximum image size is 4 megabytes
  </div>
  <% if @picture.picture_data? %>
    <div class = "field">
      <% if !@picture.picture[:thumb].nil? %>
        <%= image_tag @picture.picture_url(:thumb) %>
      <% end %>
    </div>
    <div class = "field">
      Remove attachment: <%= f.check_box :remove_picture %>
    </div>
  <% end %>

<%if false %>
  <div><strong>Concerts: </strong></div>

 <div class="field">
   <% for concert in Concert.all.order(:concert_year) %>
     <% if (true)%>
       <%= check_box_tag "picture[concert_ids][]", concert.id, @picture.concerts.include?(concert) %>
       <%= concert.concert_year.to_s + '-' + concert.name[0..20] %>
     <% end %>
     |
   <%end%>
  </div>

  <div class="field">
    <% for concert in Concert.all %>
      <% if !concert.pictures.find_by_name(picture.name).nil? %>
        <% so = picture.programs.find_by_picture_id(picture.id).picture_order
            if (so.nil?)
              picture.s_o = 0
            else
              picture.s_o = so
            end %>
        <strong><%= concert.concert_year %></strong>
        <%= f.label( " picture Order: " ) %>
        <%= f.number_field :s_o, in: 0..30, size: 3 %>
      <% end %>
    <% end %>
  </div>

  <p></p>

  <div><strong> Soloists:  </strong></div>

  <div class="field">
   <% for singer in Singer.all.order(:last_name) %>
     <% if (true)%>
       <%= check_box_tag "picture[singer_ids][]", singer.id, @picture.singers.include?(singer) %>
       <%= singer.first_name[0] + " " + singer.last_name %>
     <% end %>
     |
   <%end%>
<p></p>
<% end %>

   <div class="actions">
    <%= f.submit 'Save picture', :class => 'btn btn-success btn-sm active' %>
  </div>

<% end %>
<p></p>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>
<%= link_to "Back - Don't Save", pictures_path, :class => 'btn btn-warning btn-sm active' %>

<% if false %>
<%= link_to 'Show', @picture %> |
<% end %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Pictures</h3>
<h5>Total Count: <%= Picture.count %></h5>

<% can = policy(Picture).create? %>

<%= search_form_for @q do |f| %>
    <%= f.submit "Search by:", :class => 'btn btn-info btn-sm active' %> &nbsp &nbsp ->
    <%= f.label :caption_cont, "Caption:", :style => "display: inline-block" %>
    <%= f.search_field :caption_cont, :id => "searchfpn" %>
     <%= f.label :notes_cont, "Notes:", :style => "display: inline-block" %>
    <%= f.search_field :notes_cont, :id => "searchfpn" %>
   <% if can %>
      <%= link_to 'New Picture', new_picture_path, :class => 'btn btn-success btn-sm active' %>
    <% end %>
<% end %>

<table>
  <thead>
    <tr>
      <th><%="Picture" %></th>
      <th><%= sort_link "caption" %></th>
      <th><%= sort_link "picture_date" %></th>
      <th><%= sort_link "submitted_by" %></th>      
      <th><%= "Notes" %></th>
      <th><%= "Orig. Name" %></th>
      <th><%= "Size" %></th>
      <th><%= "Height" %></th>
      <th><%= "Width" %></th>
      <% if policy(Picture).update? %>
        <th>ID</th>
        <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    
    <% @pictures.each do |picture| %>
      <tr>
        <td>
          <% if picture.picture_data %>
            <% if !picture.picture[:thumb].nil? %>
              <%= image_tag picture.picture_url(:thumb) %> 
            <% end %>
            </td>
            <td><%= link_to "#{picture.caption[0..20]}", picture %></td>
            <td><%= picture.picture_date %></td>
            <td><%= picture.submitted_by %></td>
            <td><%= picture.notes[0..15] %></td>
            <% if !picture.picture[:original].nil? %>
              <td><%= picture.picture[:original].original_filename %></td>
              <td><%= number_with_delimiter(picture.picture[:original].size) %> kb</td> 
              <td><%= picture.picture[:original].height %></td>
              <td><%= picture.picture[:original].width %></td>
            <% end %>
          <% end %>
          <% if false %><td><%= link_to 'Show', song %></td><% end %>
          <% if policy(picture).update? %>
            <% if picture.picture_data && !picture.picture[:thumb].nil? %>
              <td><%= picture.picture[:original].id %></td>
            <% end %>
          <td><%= link_to 'Edit', edit_picture_path(picture), :class => 'btn btn-success btn-sm active' %></td>
          <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-sm active' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can %>
  <%= link_to 'New Picture', new_picture_path, :class => 'btn btn-success btn-sm active' %>
<% end %>

<% if false %>
<%= link_to 'Concerts', concerts_path %>
<%= link_to 'Singers', singers_path %>
<% end %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to "Back - Don't Save", pictures_path, :class => 'btn btn-warning btn-sm active'  %>

app/views/pictures/show.html.erb
<h3> Pictures </h3>

<p>
  <strong>Caption:</strong>
  <%= @picture.caption %>
</p>

<p>
  <strong>Picture Date:</strong>
  <%= @picture.picture_date %>  -:-
  <strong>Submitted By:</strong>
  <%= @picture.submitted_by %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @picture.notes %>
</p>

<% if @picture.picture_data && !@picture.picture[:original].nil? %>
  <p>
    <strong>Original Name:</strong>
    <%= @picture.picture[:original].original_filename %> -:-
    <strong>Size:</strong>
   <%= number_with_delimiter(@picture.picture[:original].size) %> kb -:-
    <strong>Height:</strong>
    <%= @picture.picture[:original].height %> pixels -:-
   <strong>Width:</strong>
    <%= @picture.picture[:original].width %> pixels
  </p>

  <p>
    <strong>ID:</strong>
    <%= @picture.picture[:original].id %>
  </p>

  <p>
    <% if !@picture.picture[:medium].nil? %>
      <%= image_tag @picture.picture_url(:medium) %> 
    </p><p>
      <%= link_to 'Click here for original (full size) photo', @picture.picture_url(:original) %>
    <% end %>
  </p>
<% end %>

<% if false %>
<p>
  <strong>In Concerts: </strong>
  <% @picture.concerts.order(:concert_year).each do |t| %>
    <td><%= t.concert_year.to_s + '-' + t.name %></td>
    -:- 
  <% end %>
</p>

<p>
<% for concert in Concert.all %>
      <% if !concert.pictures.find_by_name(@picture.name).nil? %>
        <% cy = concert.concert_year %>
        <% cid = concert.id %>
        <strong>picture Order 
        <%= "#{cy}" %>: </strong>
        <%= Program.find_by_picture_id_and_concert_id(@picture.id,cid).picture_order %> -:-
      <% end %>
    <% end %>
</p>

<p>
  <strong>Soloists:</strong>
  <% @picture.singers.order(:last_name).each do |t| %>
    <td><%= t.first_name[0]+" "+t.last_name %></td>
    -:-  
  <% end %>
</p>
<% end %>

<%= link_to 'Back', pictures_path, :class => 'btn btn-primary btn-sm active' %>     |   

<% if policy(Picture).update? %>
  <%= link_to 'Edit', edit_picture_path(@picture), :class => 'btn btn-warning btn-sm active' %> |
<% end %>

<% if policy(Picture).create? %>
  <%= link_to 'New picture', new_picture_path, :class => 'btn btn-success btn-sm active' %>
<% end %>

<% if false %>
<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %> |
<%= link_to 'Add New picture', new_picture_path %>
<% end %>